//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：TP_PRODCOGNIZANCE.autogenerated.cs
// author: Winform定制
// create date：2016/9/27 9:17:01
//
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
namespace Models
{
	public  class TP_PRODCOGNIZANCE
	{
		#region Data

		/// <summary>
		/// id
		/// </summary>
		private string iD;
		
		/// <summary>
		/// 产品表id
		/// </summary>
		private string rEMS_PRODUCT_ID;
		
		/// <summary>
		/// 认证名称
		/// </summary>
		private string cOGNIZANCE_NAME;
		
		/// <summary>
		/// 认证编号
		/// </summary>
		private string cOGNIZANCE_NUMBER;
		
		/// <summary>
		/// 认证类型
		/// </summary>
		private string cOGNIZANCE_TYPE;
		
		/// <summary>
		/// 认证到期时间（认证时间）
		/// </summary>
		private string cOGNIZANCE_DATE;
		
		/// <summary>
		/// 发证日期
		/// </summary>
		private string cOGNIZANCE_AWARD;
		
		/// <summary>
		/// 颁发单位
		/// </summary>
		private string cOGNIZANCE_DEPARTMENT;
		
		/// <summary>
		/// 认证文件名
		/// </summary>
		private string cOGNIZANCE_FILE_NAME;
		
		/// <summary>
		/// 认证来源
		/// </summary>
		private string cOGNIZANCE_SOURCE;
		
		/// <summary>
		/// 认证状态
		/// </summary>
		private string cOGNIZANCE_STATE;
		
		/// <summary>
		/// 创建时间
		/// </summary>
		private string cREATE_DATE;
		
		/// <summary>
		/// 版本号
		/// </summary>
		private decimal? vERSION;
		
		/// <summary>
		/// 状态
		/// </summary>
		private string sTATUS;
		
		/// <summary>
		/// 备注
		/// </summary>
		private string rEMARK;
		
		/// <summary>
		/// 必备条件
		/// </summary>
		private string tEC_REQUIREMENTS;
		
		/// <summary>
		/// 格式化类型
		/// </summary>
		private string fORMAT_TYPE;
		
		/// <summary>
		/// 认证单位
		/// </summary>
		private string cOGNIZANCE_UNIT;
		
		/// <summary>
		/// 产品类别
		/// </summary>
		private string pRODUCT_CLASSIFICATION;
		
		/// <summary>
		/// 位置
		/// </summary>
		private string lOCATION;
		
		 
		#endregion
		
		#region Properties
		
       
		/// <summary>
		/// id
		/// </summary>
		public string ID
		{
			get 
			{
				return this.iD;
			}
			set 
			{
				this.iD = value;
			}
		}

       
		/// <summary>
		/// 产品表id
		/// </summary>
		public string REMS_PRODUCT_ID
		{
			get 
			{
				return this.rEMS_PRODUCT_ID;
			}
			set 
			{
				this.rEMS_PRODUCT_ID = value;
			}
		}

       
		/// <summary>
		/// 认证名称
		/// </summary>
		public string COGNIZANCE_NAME
		{
			get 
			{
				return this.cOGNIZANCE_NAME;
			}
			set 
			{
				this.cOGNIZANCE_NAME = value;
			}
		}

       
		/// <summary>
		/// 认证编号
		/// </summary>
		public string COGNIZANCE_NUMBER
		{
			get 
			{
				return this.cOGNIZANCE_NUMBER;
			}
			set 
			{
				this.cOGNIZANCE_NUMBER = value;
			}
		}

       
		/// <summary>
		/// 认证类型
		/// </summary>
		public string COGNIZANCE_TYPE
		{
			get 
			{
				return this.cOGNIZANCE_TYPE;
			}
			set 
			{
				this.cOGNIZANCE_TYPE = value;
			}
		}

       
		/// <summary>
		/// 认证到期时间（认证时间）
		/// </summary>
		public string COGNIZANCE_DATE
		{
			get 
			{
				return this.cOGNIZANCE_DATE;
			}
			set 
			{
				this.cOGNIZANCE_DATE = value;
			}
		}

       
		/// <summary>
		/// 发证日期
		/// </summary>
		public string COGNIZANCE_AWARD
		{
			get 
			{
				return this.cOGNIZANCE_AWARD;
			}
			set 
			{
				this.cOGNIZANCE_AWARD = value;
			}
		}

       
		/// <summary>
		/// 颁发单位
		/// </summary>
		public string COGNIZANCE_DEPARTMENT
		{
			get 
			{
				return this.cOGNIZANCE_DEPARTMENT;
			}
			set 
			{
				this.cOGNIZANCE_DEPARTMENT = value;
			}
		}

       
		/// <summary>
		/// 认证文件名
		/// </summary>
		public string COGNIZANCE_FILE_NAME
		{
			get 
			{
				return this.cOGNIZANCE_FILE_NAME;
			}
			set 
			{
				this.cOGNIZANCE_FILE_NAME = value;
			}
		}

       
		/// <summary>
		/// 认证来源
		/// </summary>
		public string COGNIZANCE_SOURCE
		{
			get 
			{
				return this.cOGNIZANCE_SOURCE;
			}
			set 
			{
				this.cOGNIZANCE_SOURCE = value;
			}
		}

       
		/// <summary>
		/// 认证状态
		/// </summary>
		public string COGNIZANCE_STATE
		{
			get 
			{
				return this.cOGNIZANCE_STATE;
			}
			set 
			{
				this.cOGNIZANCE_STATE = value;
			}
		}

       
		/// <summary>
		/// 创建时间
		/// </summary>
		public string CREATE_DATE
		{
			get 
			{
				return this.cREATE_DATE;
			}
			set 
			{
				this.cREATE_DATE = value;
			}
		}

       
		/// <summary>
		/// 版本号
		/// </summary>
		public decimal? VERSION
		{
			get 
			{
				return this.vERSION;
			}
			set 
			{
				this.vERSION = value;
			}
		}

       
		/// <summary>
		/// 状态
		/// </summary>
		public string STATUS
		{
			get 
			{
				return this.sTATUS;
			}
			set 
			{
				this.sTATUS = value;
			}
		}

       
		/// <summary>
		/// 备注
		/// </summary>
		public string REMARK
		{
			get 
			{
				return this.rEMARK;
			}
			set 
			{
				this.rEMARK = value;
			}
		}

       
		/// <summary>
		/// 必备条件
		/// </summary>
		public string TEC_REQUIREMENTS
		{
			get 
			{
				return this.tEC_REQUIREMENTS;
			}
			set 
			{
				this.tEC_REQUIREMENTS = value;
			}
		}

       
		/// <summary>
		/// 格式化类型
		/// </summary>
		public string FORMAT_TYPE
		{
			get 
			{
				return this.fORMAT_TYPE;
			}
			set 
			{
				this.fORMAT_TYPE = value;
			}
		}

       
		/// <summary>
		/// 认证单位
		/// </summary>
		public string COGNIZANCE_UNIT
		{
			get 
			{
				return this.cOGNIZANCE_UNIT;
			}
			set 
			{
				this.cOGNIZANCE_UNIT = value;
			}
		}

       
		/// <summary>
		/// 产品类别
		/// </summary>
		public string PRODUCT_CLASSIFICATION
		{
			get 
			{
				return this.pRODUCT_CLASSIFICATION;
			}
			set 
			{
				this.pRODUCT_CLASSIFICATION = value;
			}
		}

       
		/// <summary>
		/// 位置
		/// </summary>
		public string LOCATION
		{
			get 
			{
				return this.lOCATION;
			}
			set 
			{
				this.lOCATION = value;
			}
		}
	


		#endregion
	}
}
